---
abstract: 'A Stringprep Profile for Internationalized Domain Names (RFC 3491)'
author:
  - 'Claus Färber <CFAERBER@cpan.org>'
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-IDN-Nameprep
no_index:
  directory:
    - eg
provides:
  Net::IDN::Nameprep:
    file: lib/Net/IDN/Nameprep.pm
    version: 1.101
requires:
  Unicode::Stringprep: 1.1
resources:
  license: http://dev.perl.org/licenses/
version: 1.101
